= Topologies for Graph Drawing

Various topologies for use with graph layout algorithms, providing different spatial structures for vertex placement.

*Defined in:* `<boost/graph/topology.hpp>`

== Description

Various topologies are provided that produce different, interesting results for graph layout algorithms. The <<square_topology,square topology>> can be used for normal display of graphs or distributing vertices for parallel computation on a process array, for instance. Other topologies, such as the <<sphere_topology,sphere topology>> (or N-dimensional <<ball_topology,ball topology>>) make sense for different problems, whereas the <<heart_topology,heart topology>> is just plain fun. One can also <<topology-concept,define a topology>> to suit other particular needs.

A topology is a description of a space on which layout can be performed. Some common two, three, and multidimensional topologies are provided, or you may create your own so long as it meets the requirements of the <<topology-concept,Topology concept>>.

[#topology-concept]
=== Topology Concept

Let `Topology` be a model of the Topology concept and let `space` be an object of type `Topology`. `p1` and `p2` are objects of associated type `point_type` (see below). The following expressions must be valid:

[cols="1,2,5"]
|===
| Expression | Type | Description

| `Topology::point_type`
| type
| The type of points in the space.

| `space.random_point()`
| point_type
| Returns a random point (usually uniformly distributed) within the space.

| `space.distance(p1, p2)`
| double
| Get a quantity representing the distance between `p1` and `p2` using a path going completely inside the space. This only needs to have the same < relation as actual distances, and does not need to satisfy the other properties of a norm in a Banach space.

| `space.move_position_toward(p1, fraction, p2)`
| point_type
| Returns a point that is a fraction of the way from `p1` to `p2`, moving along a "line" in the space according to the distance measure. `fraction` is a `double` between 0 and 1, inclusive.

|===

[#convex_topology]
=== Class template `convex_topology`

Class template `convex_topology` implements the basic distance and point movement functions for any convex topology in `Dims` dimensions. It is not itself a topology, but is intended as a base class that any convex topology can derive from. The derived topology need only provide a suitable `random_point` function that returns a random point within the space.

[source,cpp]
----
template<std::size_t Dims>
class convex_topology
{
  struct point
  {
    point() { }
    double& operator[](std::size_t i) {return values[i];}
    const double& operator[](std::size_t i) const {return values[i];}

  private:
    double values[Dims];
  };

 public:
  typedef point point_type;

  double distance(point a, point b) const;
  point move_position_toward(point a, double fraction, point b) const;
};
----

[#hypercube_topology]
=== Class template `hypercube_topology`

Class template `hypercube_topology` implements a `Dims`-dimensional hypercube. It is a convex topology whose points are drawn from a random number generator of type `RandomNumberGenerator`. The `hypercube_topology` can be constructed with a given random number generator; if omitted, a new, default-constructed random number generator will be used. The resulting layout will be contained within the hypercube, whose sides measure 2*`scaling` long (points will fall in the range [-`scaling`, `scaling`] in each dimension).

[source,cpp]
----
template<std::size_t Dims,
         typename RandomNumberGenerator = minstd_rand>
class hypercube_topology : public convex_topology<Dims>
{
public:
  explicit hypercube_topology(double scaling = 1.0);
  hypercube_topology(RandomNumberGenerator& gen, double scaling = 1.0);
  point_type random_point() const;
};
----

[#square_topology]
=== Class template `square_topology`

Class template `square_topology` is a two-dimensional hypercube topology.

[source,cpp]
----
template<typename RandomNumberGenerator = minstd_rand>
class square_topology : public hypercube_topology<2, RandomNumberGenerator>
{
 public:
  explicit square_topology(double scaling = 1.0);
  square_topology(RandomNumberGenerator& gen, double scaling = 1.0);
};
----

[#cube_topology]
=== Class template `cube_topology`

Class template `cube_topology` is a three-dimensional hypercube topology.

[source,cpp]
----
template<typename RandomNumberGenerator = minstd_rand>
class cube_topology : public hypercube_topology<3, RandomNumberGenerator>
{
 public:
  explicit cube_topology(double scaling = 1.0);
  cube_topology(RandomNumberGenerator& gen, double scaling = 1.0);
};
----

[#ball_topology]
=== Class template `ball_topology`

Class template `ball_topology` implements a `Dims`-dimensional ball. It is a convex topology whose points are drawn from a random number generator of type `RandomNumberGenerator` but reside inside the ball. The `ball_topology` can be constructed with a given random number generator; if omitted, a new, default-constructed random number generator will be used. The resulting layout will be contained within the ball with the given `radius`.

[source,cpp]
----
template<std::size_t Dims,
         typename RandomNumberGenerator = minstd_rand>
class ball_topology : public convex_topology<Dims>
{
public:
  explicit ball_topology(double radius = 1.0);
  ball_topology(RandomNumberGenerator& gen, double radius = 1.0);
  point_type random_point() const;
};
----

[#circle_topology]
=== Class template `circle_topology`

Class template `circle_topology` is a two-dimensional ball topology.

[source,cpp]
----
template<typename RandomNumberGenerator = minstd_rand>
class circle_topology : public ball_topology<2, RandomNumberGenerator>
{
 public:
  explicit circle_topology(double radius = 1.0);
  circle_topology(RandomNumberGenerator& gen, double radius = 1.0);
};
----

[#sphere_topology]
=== Class template `sphere_topology`

Class template `sphere_topology` is a three-dimensional ball topology.

[source,cpp]
----
template<typename RandomNumberGenerator = minstd_rand>
class sphere_topology : public ball_topology<3, RandomNumberGenerator>
{
 public:
  explicit sphere_topology(double radius = 1.0);
  sphere_topology(RandomNumberGenerator& gen, double radius = 1.0);
};
----

[#heart_topology]
=== Class template `heart_topology`

Class template `heart_topology` is topology in the shape of a heart. It serves as an example of a non-convex, nontrivial topology for layout.

[source,cpp]
----
template<typename RandomNumberGenerator = minstd_rand>
class heart_topology
{
 public:
  typedef unspecified point_type;

  heart_topology();
  heart_topology(RandomNumberGenerator& gen);
  point_type random_point() const;
  double distance(point_type a, point_type b) const;
  point_type move_position_toward(point_type a, double fraction, point_type b) const;
};
----
