[#sec:undirected-graph-class]
= Undirected Graph

....

undirected_graph<VertexProp, EdgeProp, GraphProp>
....

The `undirected_graph` class template is is a simplified version of
the BGL adjacency list. This class is provided for ease of use, but may
not perform as well as custom-defined adjacency list classes. Instances
of this template model the BidirectionalGraph, VertexIndexGraph, and
EdgeIndexGraph concepts.

==== Example

A simple example of creating an undirected_graph is available here
link:../../../libs/graph/example/undirected_graph.cpp[`libs/graph/example/undirected_graph.cpp`]

[source,cpp]
----

  typedef boost::undirected_graph<> Graph;
  Graph g;
  boost::graph_traits::vertex_descriptor v0 = g.add_vertex();
  boost::graph_traits::vertex_descriptor v1 = g.add_vertex();

  g.add_edge(v0, v1);
----

==== Template Parameters

[cols=",,",options="header",]
|===
|Parameter |Description |Default
|`VertexProp` |A property map for the graph vertices. | 
|`EdgeProp` |A property map for the graph edges. | 
|`GraphProp` |A property map for the graph itself. |
|===

==== Where Defined

link:../../../boost/graph/undirected_graph.hpp[`boost/graph/undirected_graph.hpp`]
