= Using SGB Graphs in BGL

The Boost Graph Library (BGL) header,
link:../../../boost/graph/stanford_graph.hpp[`<boost/graph/stanford_graph.hpp>`],
adapts a Stanford GraphBase (SGB) `Graph` pointer into a BGL-compatible
xref:concepts/VertexListGraph.adoc[VertexListGraph].  Note that a graph adaptor
*class* is _not_ used; SGB's `Graph*` itself becomes a model of
VertexListGraph.  The VertexListGraph concept is fulfilled by defining
the appropriate non-member functions for `Graph*`.

[#sec:SGB]
=== The Stanford GraphBase

"The http://www-cs-staff.stanford.edu/~knuth/sgb.html[Stanford
GraphBase] (SGB) is a collection of datasets and computer programs that
generate and examine a wide variety of graphs and networks."  The SGB
was developed and published by
http://www-cs-staff.stanford.edu/~knuth[Donald E. Knuth] in 1993.  The
fully documented source code is available for anonymous ftp from
ftp://labrea.stanford.edu/pub/sgb/sgb.tar.gz[Stanford University] and in
the book "The Stanford GraphBase, A Platform for Combinatorial
Computing," published jointly by ACM Press and Addison-Wesley Publishing
Company in 1993.  (This book contains several chapters with additional
information not available in the electronic distribution.)

[#sec:CWEB]
==== Prerequisites

The source code of SGB is written in accordance with the rules of the
http://www-cs-staff.stanford.edu/~knuth/lp.html[Literate Programming]
paradigm, so you need to make sure that your computer supports the
http://www-cs-staff.stanford.edu/~knuth/cweb.html[CWEB] system.  The
CWEB sources are available for anonymous ftp from
ftp://labrea.stanford.edu/pub/cweb/cweb.tar.gz[Stanford University]. 
Bootstrapping CWEB on Unix systems is elementary and documented in the
CWEB distribution; pre-compiled binary executables of the CWEB tools for
Win32 systems are available from
http://www.literateprogramming.com[www.literateprogramming.com].

[#sec:SGB:Installation]
==== Installing the SGB

After you have acquired the <<sec:SGB,SGB sources>> and have
installed a working <<sec:CWEB,CWEB system>> (at least the "ctangle"
processor is required), you're almost set for compiling the SGB
sources.  SGB is written in "old-style C," but the Boost Graph Library
expects to handle "modern C" and C++.  Fortunately, the SGB
distribution comes with an appropriate set of patches that convert all
the sources from "KR-C" to "ANSI-C," thus allowing for smooth
integration of the Stanford GraphBase in the Boost Graph Library.

* *Unix*: After extracting the SGB archive, but prior to invoking
"`make tests`" and "`make install`," you should say
"`ln -s PROTOTYPES/*.ch .`" in the root directory where you
extracted the SGB files (or you can simply copy the change files next to
the proper source files).  The Unix `Makefile` coming with SGB
conveniently looks for "change files" matching the SGB source files and
automatically applies them with the "ctangle" processor.  The resulting
C files will smoothly run through the compiler.
* *Win32*: The "MSVC" subdirectory of the SGB distribution contains a
complete set of "Developer Studio Projects" (and a single "Workspace"),
applicable with Microsoft Developer Studio 6.  The installation process
is documented in the accompanying file `README.MSVC`.  The "MSVC"
contribution has been updated to make use of the "PROTOTYPES" as well,
so you don't need to worry about that.

[#sec:UsingSGB]
==== Using the SGB

After you have run <<sec:SGB:Installation,the installation process>>
of the SGB, you can use the BGL graph interface with the SGB
`Graph*`,
link:../../../boost/graph/stanford_graph.hpp[`<boost/graph/stanford_graph.hpp>`],
which will be described <<sec:BGL:Interface,next>>.  All you have to
do is tell the C++ compiler where to look for the SGB
headerfiles (by default, `/usr/local/sgb/include` on Unix and the "MSVC"
subdirectory of the SGB installation on Win32) and the linker where to
find the SGB static library file (`libgb.a` on Unix and `libgb.lib` on
Win32); consult the documentation of your particular compiler about how
to do that.

[#sec:SGB:Problems]
==== Technicalities

* *Headerfile selection*: The two SGB modules `gb_graph` and
`gb_io` use the preprocessor switch `SYSV` to select either the
headerfile `<string.h>` (if `SYSV` is `++#++define`d) or the
headerfile `<strings.h>` (if `SYSV` is _not_ `++#++define`d). 
Some compilers, like `gcc`/`g++`, don't care much (`gcc`
"knows" about the "string" functions without referring to
`<string.h>`), but others, like MSVC on Win32, do (so all
"Developer Studio Projects" in the "MSVC" subdirectory of the
<<sec:SGB,SGB distribution>> appropriately define `SYSV`). You should
be careful to set (or not) `SYSV` according to the needs of your
compiler.
* *Missing include guards*: None of the SGB headerfiles uses "internal
include guards" to protect itself from multiple inclusion.  To avoid
trouble, you must _not_ `++#++include` any of the SGB headerfiles before
or after <<sec:Wrapper,the BGL wrapper>> in a compilation unit; it
will fully suffice to use the BGL interface.
* *Preprocessor macros*: The SGB headerfiles make liberal use of the
preprocessor _without_ sticking to a particular convention (like
all-uppercase names or a particular prefix).  At the time of writing,
already three of these preprocessor macros collide with the conventions
of either C++, g++, or BGL, and are fixed in
<<sec:Wrapper,the BGL wrapper>>.  We can not guarantee that no other
preprocessor-induced problems may arise (but we are willing to learn
about any such collisions).

[#sec:BGL:Interface]
=== The BGL Interface for the SGB

[#sec:Wrapper]
==== Where Defined

link:../../../boost/graph/stanford_graph.hpp[`<boost/graph/stanford_graph.hpp>`]

The main purpose of this Boost Graph Library (BGL) headerfile is to
`++#++include` all global definitions for the general stuff of the
<<sec:SGB,Stanford GraphBase>> (SGB) and its various graph generator
functions by reading all <<sec:SGB:Problems,SGB headerfiles>> as in
section 2 of the "`test_sample`" program.

On top of the SGB stuff, the BGL `stanford_graph.hpp` header adds
and defines appropriate types and functions for using the SGB graphs in
the BGL framework.  Apart from the improved interface, the
<<sec:UsingSGB,SGB (static) library>> is used "as is" in the context
of BGL.

==== Model Of

xref:concepts/VertexListGraph.adoc[Vertex List Graph] and
xref:concepts/PropertyGraph.adoc[Property Graph]. The set of property tags that
can be used with the SGB graph is described in the
<<properties,Vertex and Edge Properties>> section below.

[#sec:Example]
==== Example

The example program
link:../example/miles_span.cpp[`<example/miles_span.cpp>`]
represents the first application of the generic framework of BGL to an
SGB graph.  It uses Prim's algorithm to solve the "minimum spanning
tree" problem.  In addition, the programs
link:../../../libs/graph/example/girth.cpp[`<example/girth.cpp>`]
and
link:../example/roget_components.cpp[`<example/roget_components.cpp>`]
have been ported from the SGB.  We intend to implement more algorithms
from SGB in a generic fashion and to provide the remaining example
programs of SGB for the BGL framework.  If you would like to help, feel
free to submit your contributions!

==== Associated Types

'''''

`graph_traits<Graph++*>++::vertex_descriptor` +
 +
The type for the vertex descriptors associated with the `Graph*`. We
use the type `Vertex*` as the vertex descriptor.

'''''

`graph_traits<Graph++*>++::edge_descriptor` +
 +
The type for the edge descriptors associated with the `Graph*`. This
is the type `boost::sgb_edge`. In addition to supporting all the
required operations of a BGL edge descriptor, the `boost::sgb_edge`
class has the following constructor.

....

   sgb_edge::sgb_edge(Arc* arc, Vertex* source)
....

'''''

`graph_traits<Graph++*>++::vertex_iterator` +
 +
The type for the iterators returned by `vertices()`.

'''''

`graph_traits<Graph++*>++::out_edge_iterator` +
 +
The type for the iterators returned by `out_edges()`.

'''''

`graph_traits<Graph++*>++::adjacency_iterator` +
 +
The type for the iterators returned by `adjacent_vertices()`.

'''''

`graph_traits<Graph++*>++::vertices_size_type` +
 +
The type used for dealing with the number of vertices in the graph.

'''''

`graph_traits<Graph++*>++::edge_size_type` +
 +
The type used for dealing with the number of edges in the graph.

'''''

`graph_traits<Graph++*>++::degree_size_type` +
 +
The type used for dealing with the number of edges incident to a vertex
in the graph.

'''''

`graph_traits<Graph++*>++::directed_category` +
 +
Provides information about whether the graph is directed or undirected.
An SGB `Graph*` is directed so this type is `directed_tag`.

'''''

`graph_traits<Graph++*>++::traversal_category` +
 +
An SGB `Graph*` provides traversal of the vertex set, out edges, and
adjacent vertices. Therefore the traversal category tag is defined as
follows:

[source,cpp]
----

struct sgb_traversal_tag :
  public virtual vertex_list_graph_tag,
  public virtual incidence_graph_tag,
  public virtual adjacency_graph_tag { };
----

'''''

`graph_traits<Graph++*>++::edge_parallel_category` +
 +
This describes whether the graph class allows the insertion of parallel
edges (edges with the same source and target).  The SGB `Graph*`
does not prevent addition of parallel edges, so this type is
`allow_parallel_edge_tag`.

'''''

==== Non-Member Functions
