= `copy_graph`

[source,cpp]
----

template <class VertexListGraph, class MutableGraph>
void copy_graph(const VertexListGraph& G, MutableGraph& G_copy,
    const bgl_named_params<P, T, R>& params = all defaults)
----

This function copies all of the vertices and edges from graph `G` into
`G_copy`. Also, it copies the vertex and edge properties, either by
using the `vertex_all` and `edge_all` property maps, or by
user-supplied copy functions.

==== Where Defined

link:../../../boost/graph/copy.hpp[`boost/graph/copy.hpp`]

==== Parameters

IN: `const VertexListGraph& G`

____
A directed or undirected graph. The graph type must be a model of
xref:concepts/VertexListGraph.adoc[Vertex List Graph].
____

OUT: `MutableGraph& G_copy`

____
The resulting copy of the graph. The graph type must be a model of
xref:concepts/MutableGraph.adoc[Mutable Graph].
____

==== Named Parameters

IN: `vertex_copy(VertexCopier vc)`

____
This is a http://www.boost.org/sgi/stl/BinaryFunction.html[Binary
Function] that copies the properties of a vertex in the original graph
into the corresponding vertex in the copy. +
*Default:* `vertex_copier<VertexListGraph, MutableGraph>`
which uses the property tag `vertex_all` to access a property map
from the graph.
____

IN: `edge_copy(EdgeCopier ec)`

____
This is a http://www.boost.org/sgi/stl/BinaryFunction.html[Binary
Function] that copies the properties of an edge in the original graph
into the corresponding edge in the copy. +
*Default:* `edge_copier<VertexListGraph, MutableGraph>`
which uses the property tag `edge_all` to access a property map from
the graph.
____

IN: `vertex_index_map(VertexIndexMap i_map)`

____
The vertex index map type must be a model of
link:../../property_map/doc/ReadablePropertyMap.html[Readable Property
Map] and must map the vertex descriptors of `G` to the integers in the
half-open range `[0,num_vertices(G))`. +
*Default:* `get(vertex_index, G)`. Note: if you use this default,
make sure your graph has an internal `vertex_index` property. For
example, `adjacency_list` with `VertexList=listS` does not have an
internal `vertex_index` property.
____

UTIL/OUT: `orig_to_copy(Orig2CopyMap c)`

____
This maps vertices in the original graph to vertices in the copy.
*Default:* an
link:../../property_map/doc/iterator_property_map.html[iterator_property_map]
created from a `std::vector` of the output graph's vertex descriptor
type of size `num_vertices(g)` and using the `i_map` for the
index map.
____

==== Complexity

The time complexity is _O(V {plus} E)_.
