= Cycle Canceling for  Min Cost Max Flow

`cycle_canceling`

[source,cpp]
----

// named parameter version
template <class Graph, class P, class T, class R>
void cycle_canceling(
        Graph &g,
        const bgl_named_params<P, T, R> & params  = all defaults)

// non-named parameter version
template <class Graph, class Pred, class Distance, class Reversed, class ResidualCapacity, class Weight>
void cycle_canceling(const Graph & g, Weight weight, Reversed rev, ResidualCapacity residual_capacity, Pred pred, Distance distance)
----

The `cycle_canceling()` function calculates the minimum cost flow of
a network with given flow. See Section
xref:overview/graph_theory_review.adoc#sec:network-flow-algorithms[Network Flow
Algorithms] for a description of maximum flow. For given flow values
_f(u,v)_ function minimizes flow cost in such a way, that for each _v in
V_ the _sum ~u in V~ f(v,u)_ is preserved. Particularly if the input
flow was the maximum flow, the function produces min cost max flow. The
function calculates the flow values _f(u,v)_ for all _(u,v)_ in _E_,
which are returned in the form of the residual capacity _r(u,v) = c(u,v)
- f(u,v)_.

There are several special requirements on the input graph and property
map parameters for this algorithm. First, the directed graph _G=(V,E)_
that represents the network must be augmented to include the reverse
edge for every edge in _E_. That is, the input graph should be _G~in~ =
(V,{E U E^T^})_. The `ReverseEdgeMap` argument `rev` must map each
edge in the original graph to its reverse edge, that is _(u,v) ->
(v,u)_ for all _(u,v)_ in _E_. The `WeightMap` has to map each edge from
_E^T^_ to _-weight_ of its reversed edge. Note that edges from _E_ can
have negative weights.

If weights in the graph are nonnegative, the
xref:algorithms/successive_shortest_path_nonnegative_weights.adoc[`successive_shortest_path_nonnegative_weights()`]
might be better choice for min cost max flow.

The algorithm is described in
xref:about/bibliography.adoc#ahuja93:_network_flows[Network Flows].

In each round algorithm augments the negative cycle (in terms of weight)
in the residual graph. If there is no negative cycle in the network, the
cost is optimized.

Note that, although we mention capacity in the problem description, the
actual algorithm doesn't have to now it.

In order to find the cost of the result flow use:
xref:algorithms/find_flow_cost.adoc[`find_flow_cost()`].

==== Where Defined

link:../../../boost/graph/successive_shortest_path_nonnegative_weights.hpp[`boost/graph/successive_shortest_path_nonnegative_weights.hpp`]

==== Parameters

IN: `Graph& g`

____
A directed graph. The graph's type must be a model of
xref:concepts/VertexListGraph.adoc[VertexListGraph] and
xref:concepts/IncidenceGraph.adoc[IncidenceGraph] For each edge _(u,v)_ in the
graph, the reverse edge _(v,u)_ must also be in the graph.
____

==== Named Parameters

IN/OUT: `residual_capacity_map(ResidualCapacityEdgeMap res)`

____
This maps edges to their residual capacity. The type must be a model of
a mutable link:../../property_map/doc/LvaluePropertyMap.html[Lvalue
Property Map]. The key type of the map must be the graph's edge
descriptor type. +
*Default:* `get(edge_residual_capacity, g)`
____

IN: `reverse_edge_map(ReverseEdgeMap rev)`

____
An edge property map that maps every edge _(u,v)_ in the graph to the
reverse edge _(v,u)_. The map must be a model of constant
link:../../property_map/doc/LvaluePropertyMap.html[Lvalue Property Map].
The key type of the map must be the graph's edge descriptor type. +
*Default:* `get(edge_reverse, g)`
____

IN: `weight_map(WeightMap w)`

____
The weight (also know as ++``++length'' or ++``++cost'') of each edge in
the graph. The `WeightMap` type must be a model of
link:../../property_map/doc/ReadablePropertyMap.html[Readable Property
Map]. The key type for this property map must be the edge descriptor of
the graph. The value type for the weight map must be _Addable_ with the
distance map's value type. +
*Default:* `get(edge_weight, g)` +
____

UTIL: `predecessor_map(PredEdgeMap pred)`

____
Use by the algorithm to store augmenting paths. The map must be a model
of mutable link:../../property_map/doc/LvaluePropertyMap.html[Lvalue
Property Map]. The key type must be the graph's vertex descriptor type
and the value type must be the graph's edge descriptor type. +
*Default:* an
link:../../property_map/doc/iterator_property_map.html[`iterator_property_map`]
created from a `std::vector` of edge descriptors of size
`num_vertices(g)` and using the `i_map` for the index map.
____

UTIL: `distance_map(DistanceMap d_map)`

____
The shortest path weight from the source vertex `s` to each vertex in
the graph `g` is recorded in this property map. The shortest path weight
is the sum of the edge weights along the shortest path. The type
`DistanceMap` must be a model of
link:../../property_map/doc/ReadWritePropertyMap.html[Read/Write
Property Map]. The vertex descriptor type of the graph needs to be
usable as the key type of the distance map. *Default:*
link:../../property_map/doc/iterator_property_map.html[`iterator_property_map`]
created from a `std::vector` of the `WeightMap`'s value type of size
`num_vertices(g)` and using the `i_map` for the index map. +
____

IN: `vertex_index_map(VertexIndexMap i_map)`

____
Maps each vertex of the graph to a unique integer in the range
`[0, num_vertices(g))`. This property map is only needed if the
default for the distance or predecessor map is used. The vertex index
map must be a model of
link:../../property_map/doc/ReadablePropertyMap.html[Readable Property
Map]. The key type of the map must be the graph's vertex descriptor
type. +
*Default:* `get(vertex_index, g)` Note: if you use this default,
make sure your graph has an internal `vertex_index` property. For
example, `adjacency_list` with `VertexList=listS` does not have an
internal `vertex_index` property.
____

==== Complexity

In the integer capacity and weight case, if _C_ is the initial cost of
the flow, then the complexity is _O(C * ++|++V++|++ *
++|++E++|++)_, where _O(++|++E++|*++ ++|++V++|++)_ is the complexity of
the bellman ford shortest paths algorithm and _C_ is upper bound on
number of iteration. In many real world cases number of iterations is
much smaller than _C_.

==== Example

The program in
link:../example/cycle_canceling_example.cpp[`example/cycle_canceling_example.cpp`].

==== See Also

xref:algorithms/successive_shortest_path_nonnegative_weights.adoc[`successive_shortest_path_nonnegative_weights()`] +
xref:algorithms/find_flow_cost.adoc[`find_flow_cost()`].
