= `is_bipartite`

[source,cpp]
----

// Version with a colormap to retrieve the bipartition
template <typename Graph, typename IndexMap, typename PartitionMap>
bool is_bipartite (const Graph& graph, const IndexMap index_map, PartitionMap partition_map)

template <typename Graph, typename IndexMap>
bool is_bipartite (const Graph& graph, const IndexMap index_map)

// Version which uses the internal index map
template <typename Graph>
bool is_bipartite (const Graph& graph);
----

The `is_bipartite()` functions tests a given graph for bipartiteness
using a DFS-based coloring approach.

An undirected graph is bipartite if one can partition its set of
vertices into two sets "left" and "right", such that each edge goes from
either side to the other. Obviously, a two-coloring of the graph is
exactly the same as a two-partition. `is_bipartite()` tests whether
such a two-coloring is possible and can return it in a given property
map.

The bipartition is recorded in the color map `partition_map`, which
will contain a two-coloring of the graph, i.e. an assignment of _black_
and _white_ to the vertices such that no edge is monochromatic. The
predicate whether the graph is bipartite is the return value of the
function.

==== Where Defined

link:../../../boost/graph/bipartite.hpp[`boost/graph/bipartite.hpp`]

==== Parameters

IN: `const Graph& graph`

____
An undirected graph. The graph type must be a model of
xref:concepts/VertexListGraph.adoc[Vertex List Graph] and
xref:concepts/IncidenceGraph.adoc[Incidence Graph]. +
____

IN: `const IndexMap index_map`

____
This maps each vertex to an integer in the range
`[0, num_vertices(graph))`. The type `VertexIndexMap` must be a
model of link:../../property_map/doc/ReadablePropertyMap.html[Readable
Property Map]. The value type of the map must be an integer type. The
vertex descriptor type of the graph needs to be usable as the key type
of the map. +
____

OUT: `PartitionMap partition_map`

____
The algorithm tests whether the graph is bipartite and assigns each
vertex either a white or a black color, according to the partition. The
`PartitionMap` type must be a model of
link:../../property_map/doc/ReadablePropertyMap.html[Readable Property
Map] and link:../../property_map/doc/WritablePropertyMap.html[Writable
Property Map] The value type must model
xref:auxiliary/ColorValue.adoc[ColorValue].
____

==== Complexity

The time complexity for the algorithm is _O(V + E)_.

==== See Also

xref:algorithms/find_odd_cycle.adoc[`find_odd_cycle()`]

==== Example

The file link:../example/bipartite_example.cpp[`examples/bipartite.cpp`]
contains an example of testing an undirected graph for bipartiteness. 

'''''

Copyright © 2010 Matthias Walter (xammy@xammy.homelinux.net)
