= `make_biconnected_planar`

[source,cpp]
----

template <typename Graph, typename PlanarEmbedding, typename EdgeIndexMap, typename AddEdgeVisitor>
void make_biconnected_planar(Graph& g, PlanarEmbedding embedding, EdgeIndexMap em, AddEdgeVisitor& vis);
----

A graph _G_ is biconnected if, for every pair of vertices _u,v_ in _G_,
there is a cycle containing both _u_ and _v_. Alternatively, a graph is
biconnected if it is connected and cannot be made disconnected by
removing any single vertex. `make_biconnected_planar` takes a
xref:algorithms/make_connected.adoc[connected] xref:algorithms/planar_graphs.adoc[planar]
graph `g` as input and adds zero or more edges to make `g` biconnected
while preserving planarity.

The default behavior of `make_biconnected_planar` is to modify
the graph `g` by calling `add_edge(u,v,g)` for every pair of
vertices _(u,v)_ where an edge needs to be added to make `g`
biconnected. This behavior can be overriden by providing a vistor as the
`AddEdgeVisitor` parameter. The only requirement for an `AddEdgeVisitor`
is that it define a member function with the following signature:

[source,cpp]
----

template <typename Graph, typename Vertex>
void visit_vertex_pair(Vertex u, Vertex v, Graph& g);
----

This event point can also be used as a hook to update the underlying
edge index map automatically as edges are added. See the documentation
for the xref:visitors/AddEdgeVisitor.adoc[AddEdgeVisitor] concept for more
information.

==== Where Defined

link:../../../boost/graph/make_biconnected_planar.hpp[`boost/graph/make_biconnected_planar.hpp`]

==== Parameters

IN/OUT: `Graph& g`

____
An undirected graph. The graph type must be a model of
xref:concepts/VertexListGraph.adoc[Vertex List Graph],
xref:concepts/IncidenceGraph.adoc[Incidence Graph], and a
xref:concepts/MutableGraph.adoc[Mutable Graph] +
____

IN: `PlanarEmbedding embedding`

____
A model of xref:auxiliary/PlanarEmbedding.adoc[PlanarEmbedding].
____

IN: `EdgeIndexMap vm`

____
A link:../../property_map/doc/ReadablePropertyMap.html[Readable Property
Map] that maps edges from `g` to distinct integers in the range
`[0, num_edges(g) )` +
*Default*: `get(edge_index,g)` +
____

IN: `AddEdgeVisitor`

____
A model of xref:visitors/AddEdgeVisitor.adoc[AddEdgeVisitor] . +
*Default*: `default_add_edge_visitor`, a class defines
`visit_vertex_pair` to dispatch its calls to `add_edge`.
____

==== Complexity

On a planar graph with _n_ vertices, `make_biconnected_planar`
runs in time _O(n)_

==== Example

link:../example/make_biconnected_planar.cpp[`examples/make_biconnected_planar.cpp`]

==== See Also

xref:algorithms/planar_graphs.adoc[Planar Graphs in the Boost Graph Library] 

'''''

Copyright © 2007 Aaron Windsor ( aaron.windsor@gmail.com)
