= SSCA Graph Generator

Generate graphs following the Scalable Synthetic Compact Applications (SSCA#2) benchmark model.

Defined in `<boost/graph/ssca_graph_generator.hpp>`

'''

=== Synopsis

[source,cpp]
----
template <typename RandomGenerator, typename Graph>
class ssca_iterator;

ssca_iterator(RandomGenerator& gen, vertices_size_type totVertices,
    vertices_size_type maxCliqueSize, double probUnidirectional,
    int maxParallelEdges, double probIntercliqueEdges);
----

[cols="1,2,5"]
|===
| Direction | Parameter | Description

| IN | `RandomGenerator& gen`             | A random number generator.
| IN | `vertices_size_type totVertices`    | Total number of vertices.
| IN | `vertices_size_type maxCliqueSize`  | Maximum size of generated cliques.
| IN | `double probUnidirectional`         | Probability that an intra-clique edge is unidirectional.
| IN | `int maxParallelEdges`              | Maximum number of parallel edges between two vertices.
| IN | `double probIntercliqueEdges`       | Probability of generating inter-clique edges.
|===

'''

== Description

The SSCA#2 benchmark generates graphs with a clustered structure: dense cliques
connected by sparse inter-clique edges. This models certain real-world networks
such as social graphs.

The generator first creates random cliques of varying sizes (up to `maxCliqueSize`),
then adds inter-clique edges with probability `probIntercliqueEdges`.

== Example

[source,cpp]
----
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/ssca_graph_generator.hpp>
#include <boost/random/mersenne_twister.hpp>

typedef boost::adjacency_list<> Graph;
boost::mt19937 gen;

boost::ssca_iterator<boost::mt19937, Graph> start(
    gen, 100, 5, 0.5, 5, 0.1);
boost::ssca_iterator<boost::mt19937, Graph> end;

Graph g(start, end, 100);
----

== See Also

* xref:auxiliary/rmat_generator.adoc[R-MAT] -- another benchmark graph generator
* xref:auxiliary/small_world_generator.adoc[Small World] -- Watts-Strogatz model
