#ifdef BOOST_GRAPH_ITERATION_MACROS_HPP

#undef BOOST_GRAPH_ITERATION_MACROS_HPP
#undef BGL_CAT
#undef BGL_FIRST
#undef BGL_LAST
#undef BGL_FORALL_VERTICES
#undef BGL_FORALL_EDGES
#undef BGL_FORALL_ADJACENT
#undef BGL_FORALL_OUTEDGES
#undef BGL_FORALL_INEDGES

#endif
