output:
  dir: ./build/site

site:
  title: Boost.Graph Documentation
  start_page: graph::index.adoc

content:
  sources:
    - url: ..
      start_path: doc
      branches: HEAD

asciidoc:
  attributes:
    source-highlighter: highlight.js

ui:
  bundle:
    url: https://github.com/boostorg/website-v2-docs/releases/download/ui-master/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
