output:
  dir: ./build/site

site:
  title: Boost.Graph Documentation
  start_page: graph::index.adoc

antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true

content:
  sources:
    - url: ..
      start_path: doc
      branches: HEAD
      edit_url: 'https://github.com/boostorg/graph/edit/develop/{path}'

asciidoc:
  attributes:
    source-highlighter: highlight.js

ui:
  bundle:
    url: https://github.com/boostorg/unordered-ui-bundle/raw/c80db72a7ba804256beb36e3a46d9c7df265d8d7/ui-bundle.zip
    snapshot: true
