= bfs_visitor

....

bfs_visitor<EventVisitorList>
....

This class is an adapter that converts a list of
xref:visitors/EventVisitor.adoc[EventVisitor]s (constructed using `std::pair`)
into a xref:visitors/BFSVisitor.adoc[BFSVisitor].

==== Example

This is an excerpt from link:../example/bfs.cpp[`examples/bfs.cpp`]
where three event-visitors are combined to make a BFS visitor. The
functions `boost::record_distances`,
`boost::record_predecessors`, and `copy_graph` are all functions
that create an event visitor.

[source,cpp]
----

  // Construct graph G and obtain the source vertex s ...

  boost::breadth_first_search(G, s,
   boost::make_bfs_visitor(
    std::make_pair(boost::record_distances(d, boost::on_tree_edge()),
    std::make_pair(boost::record_predecessors(p.begin(),
                                              boost::on_tree_edge()),
                   copy_graph(G_copy, boost::on_examine_edge())))) );
----

==== Model of

xref:visitors/BFSVisitor.adoc[BFSVisitor]

==== Template Parameters

[cols=",,",options="header",]
|===
|Parameter |Description |Default
|`EventVisitorList` |A list of xref:visitors/EventVisitor.adoc[EventVisitor]'s
created with `std::pair`. |xref:visitors/null_visitor.adoc[`null_visitor`]
|===

==== Where Defined

link:../../../boost/graph/breadth_first_search.hpp[`boost/graph/breadth_first_search.hpp`]

==== Member Functions

This class implements all of the member functions required by
xref:visitors/BFSVisitor.adoc[BFSVisitor]. In each function the appropriate
event is dispatched to the xref:visitors/EventVisitor.adoc[EventVisitor] in the
EventVisitorList.

==== Non-Member Functions

[width="100%",cols="50%,50%",options="header",]
|===
|Function |Description
|` template <class EventVisitorList>` +
`bfs_visitor<EventVisitorList>` +
`make_bfs_visitor(EventVisitorList ev_list); ` |Returns the
event visitor list adapted to be a BFS visitor.
|===

==== See Also

xref:visitors/visitor_concepts.adoc[Visitor concepts]

The following are event visitors:
xref:visitors/predecessor_recorder.adoc[`predecessor_recorder`],
xref:visitors/distance_recorder.adoc[`distance_recorder`],
xref:visitors/time_stamper.adoc[`time_stamper`], and
xref:visitors/property_writer.adoc[`property_writer`].
