= edge_predecessor_recorder

....

edge_predecessor_recorder<PredEdgeMap, EventTag>
....

This is an xref:visitors/EventVisitor.adoc[EventVisitor] that records the
predecessor (or parent) edge of a vertex in a property map. This is
particularly useful in graph search algorithms where recording the
predecessors is an efficient way to encode the search tree that was
traversed during the search. The edge predecessor recorder is typically
used with the `on_tree_edge` or `on_relax_edge` events
and cannot be used with vertex events. This visitor is meant to be used
instead of xref:visitors/predecessor_recorder.adoc[`predecessor_recorder`]
when a graph has parallel edges and it is necessary to know which
incoming edge a search algorithm used to get to a particular vertex.

`edge_predecessor_recorder` can be used with graph algorithms by
wrapping it with an algorithm-specific adaptor, such as
xref:visitors/bfs_visitor.adoc[`bfs_visitor`] and
xref:visitors/dfs_visitor.adoc[`dfs_visitor`]. Also, this event visitor can
be combined with other event visitors using `std::pair` to form an
EventVisitorList.

Algorithms such as Dijkstra's and breadth-first search will not assign a
predecessor edge to the source vertex (which is the root of the search
tree). It is often useful to initialize the source vertex's predecessor
to a special value, thereby identifying the root vertex. When using an
algorithm like depth-first search that creates a forest (multiple search
trees) it is useful to do the same for every vertex. This way all the
root nodes can be distinguished.

==== Model of

xref:visitors/EventVisitor.adoc[EventVisitor]

==== Where Defined

link:../../../boost/graph/visitors.hpp[`boost/graph/visitors.hpp`]

==== Template Parameters

[cols=",,",options="header",]
|===
|Parameter |Description |Default
|`PredEdgeMap` |A
link:../../property_map/doc/WritablePropertyMap.html[WritablePropertyMap]
where the key and value types are the vertex and edge descriptor types,
respectively, of the graph. | 

|`EventTag` |The tag to specify when the
`edge_predecessor_recorder` should be applied during the graph
algorithm. `EventTag` must be an edge event. | 
|===

=== Associated Types

[cols=",",options="header",]
|===
|Type |Description
|`edge_predecessor_recorder::event_filter` |This will be the
same type as the template parameter `EventTag`.
|===

==== Member Functions

[width="100%",cols="50%,50%",options="header",]
|===
|Member |Description
|` edge_predecessor_recorder(PredEdgeMap pa); ` |Construct an
edge predecessor recorder object with predecessor property map `pa`.

|` template <class Edge, class Graph>` +
`void operator()(Edge e, const Graph& g); ` |Given edge _e = (u,v)_,
this records _e_ as the predecessor (or parent) edge of _v_.
|===

==== Non-Member Functions

[width="100%",cols="50%,50%",options="header",]
|===
|Function |Description
|` template <class PredEdgeMap, class Tag>` +
`edge_predecessor_recorder<PredEdgeMap, Tag>` +
`record_edge_predecessors(PredEdgeMap pa, Tag); ` |A convenient
way to create a `edge_predecessor_recorder`.
|===

==== See Also

xref:visitors/visitor_concepts.adoc[Visitor concepts]

The following are other event visitors:
xref:visitors/distance_recorder.adoc[`distance_recorder`],
xref:visitors/time_stamper.adoc[`time_stamper`], and
xref:visitors/property_writer.adoc[`property_writer`].
