= predecessor_recorder

....

predecessor_recorder<PredecessorMap, EventTag>
....

This is an xref:visitors/EventVisitor.adoc[EventVisitor] that records the
predecessor (or parent) of a vertex in a predecessor property map. This
is particularly useful in graph search algorithms where recording the
predecessors is an efficient way to encode the search tree that was
traversed during the search. The predecessor recorder is typically used
with the `on_tree_edge` or `on_relax_edge` events and
cannot be used with vertex events.

`predecessor_recorder` can be used with graph algorithms by wrapping
it with an algorithm-specific adaptor, such as
xref:visitors/bfs_visitor.adoc[`bfs_visitor`] and
xref:visitors/dfs_visitor.adoc[`dfs_visitor`]. Also, this event visitor can
be combined with other event visitors using `std::pair` to form an
EventVisitorList.

Algorithms such as Dijkstra's and breadth-first search will not assign a
predecessor to the source vertex (which is the root of the search tree).
It is often useful to initialize the source vertex's predecessor to
itself, thereby identifying the root vertex as the only vertex which is
its own parent. When using an algorithm like depth-first search that
creates a forest (multiple search trees) it is useful to initialize the
predecessor of every vertex to itself. This way all the root nodes can
be distinguished.

==== Example

See the example for xref:visitors/bfs_visitor.adoc[`bfs_visitor`].

==== Model of

xref:visitors/EventVisitor.adoc[EventVisitor]

==== Where Defined

link:../../../boost/graph/visitors.hpp[`boost/graph/visitors.hpp`]

==== Template Parameters

[cols=",,",options="header",]
|===
|Parameter |Description |Default
|`PredecessorMap` |A
link:../../property_map/doc/WritablePropertyMap.html[WritablePropertyMap]
where the key type and the value type are the vertex descriptor type of
the graph. | 

|`EventTag` |The tag to specify when the `predecessor_recorder`
should be applied during the graph algorithm. `EventTag` must be an edge
event. | 
|===

=== Associated Types

[cols=",",options="header",]
|===
|Type |Description
|`predecessor_recorder::event_filter` |This will be the same
type as the template parameter `EventTag`.
|===

==== Member Functions

[width="100%",cols="50%,50%",options="header",]
|===
|Member |Description
|` predecessor_recorder(PredecessorMap pa); ` |Construct a
predecessor recorder object with predecessor property map `pa`.

|` template <class Edge, class Graph>` +
`void operator()(Edge e, const Graph& g); ` |Given edge _e = (u,v)_,
this records _u_ as the predecessor (or parent) of _v_.
|===

==== Non-Member Functions

[width="100%",cols="50%,50%",options="header",]
|===
|Function |Description
|` template <class PredecessorMap, class Tag>` +
`predecessor_recorder<PredecessorMap, Tag>` +
`record_predecessors(PredecessorMap pa, Tag); ` |A convenient way to
create a `predecessor_recorder`.
|===

==== See Also

xref:visitors/visitor_concepts.adoc[Visitor concepts]

The following are other event visitors:
xref:visitors/distance_recorder.adoc[`distance_recorder`],
xref:visitors/time_stamper.adoc[`time_stamper`], and
xref:visitors/property_writer.adoc[`property_writer`].
