= property_writer

....

property_writer<PropertyMap, OutputIterator, EventTag>
....

This is an xref:visitors/EventVisitor.adoc[EventVisitor] that can be used to
output the property of a vertex or edge at some event-point within an
algorithm.

`property_writer` can be used with graph algorithms by wrapping it
with the algorithm-specific adaptor, such as
xref:visitors/bfs_visitor.adoc[`bfs_visitor`] and
xref:visitors/dfs_visitor.adoc[`dfs_visitor`]. Also, this event visitor can
be combined with other event visitors using `std::pair` to form an
EventVisitorList.

==== Example

The following is an excerpt from
link:../example/dave.cpp[`examples/dave.cpp`].

[source,cpp]
----

  std::ostream_iterator cout_int(std::cout, " ");
  std::ostream_iterator cout_char(std::cout, " ");

  boost::breadth_first_search
    (G, vertex(a, G), make_bfs_visitor(
     std::make_pair(write_property(name, cout_char, on_discover_vertex()),
     std::make_pair(write_property(distance.begin(), cout_int,
                                   on_discover_vertex()),
     std::make_pair(print_edge(name, std::cout, on_examine_edge()),
                    print_endl(std::cout, on_finish_vertex()
                    ))))));
----

==== Model of

xref:visitors/EventVisitor.adoc[EventVisitor]

==== Where Defined

link:../../../boost/graph/visitors.hpp[`boost/graph/visitors.hpp`]

==== Template Parameters

[cols=",,",options="header",]
|===
|Parameter |Description |Default
|`PropertyMap` |A
link:../../property_map/doc/ReadablePropertyMap.html[ReadablePropertyMap]
where the `key_type` is the vertex descriptor type or edge
descriptor of the graph (depending on the kind of event tag) and the
`value_type` of the property is convertible to the `value_type`
of the `OutputIterator`. | 

|`OutputIterator` |The iterator type used to write out the property
values, which must be a model of
http://www.boost.org/sgi/stl/OutputIterator.html[OutputIterator]. | 

|`EventTag` |The tag to specify when the `property_writer` should be
applied during the graph algorithm. | 
|===

=== Associated Types

[cols=",",options="header",]
|===
|Type |Description
|`property_writer::event_filter` |This will be the same type as
the template parameter `EventTag`.
|===

==== Member Functions

[width="100%",cols="50%,50%",options="header",]
|===
|Member |Description
|` property_writer(PropertyMap pa, OutputIterator out); ` |Construct
a property writer object with the property map `pa` and output iterator
`out`.

|` template <class X, class Graph>` +
`void operator()(X x, const Graph& g); ` |This writes the property value
for `x` to the output iterator. +
`*out++ = get(pa, x);`
|===

==== Non-Member Functions

[width="100%",cols="50%,50%",options="header",]
|===
|Function |Description
|` template <class PropertyMap, class OutputIterator, class Tag>` +
`property_writer<PropertyMap, OutputIterator, Tag>` +
`write_property(PropertyMap pa, OutputIterator out, Tag); ` |A
convenient way to create a `property_writer`.
|===

==== See Also

xref:visitors/visitor_concepts.adoc[Visitor concepts]

The following are other event visitors:
xref:visitors/distance_recorder.adoc[`distance_recorder`],
xref:visitors/predecessor_recorder.adoc[`predecessor_recorder`], and
xref:visitors/time_stamper.adoc[`time_stamper`].
