= tsp_tour_visitor

....

tsp_tour_visitor<OutputIterator>
....

This type is a simple TSP tour visitor. It supplies the OutputIterator
with the vertices of the tour.

==== Example

[source,cpp]
----

std::vector<Vertex> c;
boost::metric_tsp_approx
  (g, get(edge_weight, g), make_tsp_tour_visitor(std::back_inserter(c));
----

==== Model of

xref:visitors/TSPTourVisitor.adoc[TSP Tour Visitor]

==== Template Parameters

[cols=",,",options="header",]
|===
|Parameter |Description |Default
|`OutputIterator` |An OutputIterator |None
|===

==== Where Defined

link:../../../boost/graph/metric_tsp_approx.hpp[`boost/graph/metric_tsp_approx.hpp`]

==== Member Functions

This class implements all of the member functions required by
xref:visitors/TSPTourVisitor.adoc[TSPTourVisitor].

==== Non-Member Functions

[width="100%",cols="50%,50%",options="header",]
|===
|Function |Description
|` template <typename OutputIterator>` +
`tsp_tour_visitor<OutputIterator>` +
`make_tsp_tour_visitor(OutputIterator iter) ` |Returns a
simple tsp_tour_visitor that records the TSP tour in the
OutputIterator parameter
|===

==== See Also

None
