[#sec:visitor-concepts]
= Visitor Concepts


The visitor concepts plays the same role in BGL as
http://www.boost.org/sgi/stl/functors.html[functors] play in the STL.
Functors provide a mechanism for extending an algorithm; for customizing
what is done at each step of the algorithm. Visitors allow the user to
insert their own operations at various steps within a graph algorithm.
Unlike the STL algorithms, graph algorithms typically have multiple
event points where one may want to insert a call-back via a functor.
Therefore visitors do not have a single `operator()` method like a
functor, but instead have several methods that correspond to the various
event points. Each algorithm has a different set of event points, which
are described by the following visitor concepts:

* xref:visitors/BFSVisitor.adoc[BFS Visitor]
* xref:visitors/DFSVisitor.adoc[DFS Visitor]
* xref:visitors/DijkstraVisitor.adoc[Dijkstra Visitor]
* xref:visitors/BellmanFordVisitor.adoc[Bellman Ford Visitor]
* xref:visitors/AStarVisitor.adoc[A* Visitor]
* xref:visitors/EventVisitor.adoc[Event Visitor]
* xref:visitors/PlanarFaceVisitor.adoc[Planar Face Visitor]
* xref:visitors/TSPTourVisitor.adoc[TSP Tour Visitor]
