= History

The Boost Graph Library began its life as the Generic Graph Component
Library (GGCL), a software project at the
https://web.archive.org/web/20010516042117/http://www.lsc.nd.edu/[Lab
for Scientific Computing (LSC)] at the University of Notre Dame, under
the direction of Professor https://homes.cs.washington.edu/~al75[Andrew
Lumsdaine]. The Lab's research directions include numerical linear
algebra, parallel computing, and software engineering (including generic
programming).

Soon after the Standard Template Library was released, work began at the
LSC to apply generic programming to scientific computing. The
https://en.wikipedia.org/wiki/Matrix_Template_Library[Matrix Template
Library] (Jeremy Siek's masters thesis) was one of the first projects.
Many of the lessons learned during construction of the MTL were applied
to the design and implementation of the GGCL.

Graph algorithms play an important role in sparse matrix computations,
so the LSC had a need for a good graph library. However, none of the
available graph libraries (LEDA, GTL, Stanford GraphBase) were written
using the generic programming style of the STL, and hence did not
fulfill the flexibility and high-performance requirements of the LSC.
Others were also expressing interest in a generic C++ graph library.
There had also been earlier work in the area of generic graph algorithms,
including some codes written by Alexander Stepanov, and Dietmar Kühl's
masters thesis.

With this in mind, and motivated by homework assignments in his
algorithms class, Jeremy began prototyping an interface and some graph
classes in the spring of 1998. Lie-Quan Lee then developed the first
version of GGCL, which became his masters thesis project.

The following year, Jeremy went to work for SGI with Alexander Stepanov
and Matt Austern. During this time Alex's disjoint-sets based connected
components algorithm was added to GGCL, and Jeremy began working on the
concept documentation for GGCL similar to Matt's STL documentation.

While working at SGI, Jeremy heard about Boost and was excited to find a
group of people interested in creating high-quality C++ libraries. At
Boost there were several people interested in generic graph algorithms,
most notably Dietmar Kühl. Some discussions about generic interfaces for
graph structures resulted in a revision of GGCL which closely resembles
the current Boost Graph Library interface.

On September 4, 2000 GGCL passed the Boost formal review and became the
Boost Graph Library (BGL). The first release of BGL was September 27,
2000.
