= read_dimacs_max_flow and read_dimacs_min_cut

`read_dimacs_max_flow`

[source,cpp]
----

//reads a graph with attached edge_capacity properties from an std::istream
template <class Graph, class CapacityMap, class ReverseEdgeMap>
int read_dimacs_max_flow(Graph& g,
                         CapacityMap capacity,
                         ReverseEdgeMap reverse_edge,
                         typename graph_traits::vertex_descriptor& src,
                         typename graph_traits::vertex_descriptor& sink,
                         std::istream& in=std::cin)

//reads a graph with attached edge_capacity properties from an std::istream
template <class Graph, class CapacityMap, class ReverseEdgeMap>
int read_dimacs_min_cut(Graph& g,
                        CapacityMap capacity,
                        ReverseEdgeMap reverse_edge,
                        std::istream& in=std::cin)
----

These functions read a BGL graph object from a max-flow or min-cut
problem description in extended dimacs format. (see
https://web.archive.org/web/20120102213028/http://www.avglab.com/andrew/CATS/maxflow_formats.htm[`Goldberg's site`]
for more information). For each edge found in the file an additional
reverse_edge is added and set in the reverse_edge map. For
max-flow problems, source and sink vertex descriptors are set according
to the dimacs file.

==== Where Defined

link:../../../boost/graph/read_dimacs.hpp[`boost/graph/read_dimacs.hpp`]

==== Parameters

IN: `Graph& g`

____
A directed or undirected graph. The graph's type must be a model of
xref:concepts/IncidenceGraph.adoc[IncidenceGraph].
____

OUT: `CapacityMap capacity`

____
A property map that models
link:../../property_map/doc/LvaluePropertyMap.html[mutable Lvalue
Property Map] whose key type is the edge descriptor of the graph. +
____

OUT: `ReverseEdgeMap reverse_edge`

____
A property map that models
link:../../property_map/doc/LvaluePropertyMap.html[mutable Lvalue
Property Map] whose key and value type is the edge descriptor of the
graph. This map stores the corresponding reverse edge for each each in
Graph g. +
____

OUT: `vertex_descriptor& src`

____
A graph vertex that will be set to the source of a max-flow problem.
____

OUT: `vertex_descriptor& sink`

____
A graph vertex that will be set to the sink of a max-flow problem.
____

IN: `std::istream& in`

____
A standard `std::istream` object. +
*Default*: `std::cin (for backward compatibility)`
____

==== Example

A short link:../example/read_write_dimacs-eg.cpp[example] which uses
read_dimacs and write_dimacs is located in the examples
directory.

==== See Also

xref:io/write_dimacs.adoc[`write_dimacs`]
