= write_dimacs_max_flow

`write_dimacs_max_flow`

[source,cpp]
----

//outputs a graph with including edge_capacity properties to an std::ostream
template < typename Graph, typename CapacityMap, typename IndexMap >
void write_dimacs_max_flow(Graph& g,
                         CapacityMap capacity,
                         IndexMap idx,
                         typename graph_traits::vertex_descriptor& src,
                         typename graph_traits::vertex_descriptor& sink,
                         std::ostream& out)
----

This method writes a BGL graph object as an max-flow problem into an
output stream in extended dimacs format (see
https://web.archive.org/web/20120102213028/http://www.avglab.com/andrew/CATS/maxflow_formats.htm[`Goldbergs site`]
for more information). The output can be read in again using the
link:../../../boost/graph/read_dimacs.hpp[`boost/graph/read_dimacs.hpp`]
method.

==== Where Defined

link:../../../boost/graph/write_dimacs.hpp[`boost/graph/write_dimacs.hpp`]

==== Parameters

IN: `Graph& g`

____
A directed or undirected graph. The graph's type must be a model of
xref:concepts/VertexListGraph.adoc[VertexListGraph] and
xref:concepts/EdgeListGraph.adoc[EdgeListGraph], as num_vertices(Graph) and
num_edges(Graph) is used inside. <<1,[1>>]
____

IN: `CapacityMap capacity`

____
A property map that models
link:../../property_map/doc/ReadablePropertyMap.html[Readable Property
Map] whose key type is the edge descriptor of the graph and whose value
type can be written to a stream. +
____

IN: `IndexMap epw`

____
A property map that models
link:../../property_map/doc/ReadablePropertyMap.html[Readable Property
Map] whose key type is the vertex descriptor of the graph and whose
value type can be written to a stream. +
____

OUT: `std::ostream& out`

____
A standard `std::ostream` object.
____

==== Example

A short link:../example/read_write_dimacs-eg.cpp[example] which uses
read_dimacs and write_dimacs is located in the examples
directory.

==== See Also

xref:io/read_dimacs.adoc[`read_dimacs`]

==== Notes

[#1]#[1]# As num_edges() and num_vertices() is used
inside which returns values for the unfiltered graph (instead of the
filtered), this method cannot be used with a
xref:adaptors/filtered_graph.adoc[filtered_graph]See
xref:adaptors/filtered_graph.adoc#2[filtered_graph Note [2]] for
the reason.
